Fix some zh-Hant translation
aonez/Keka pull request #1339
Opened 2023-10-01 16:12 UTC by PeterDaveHello

It looks like the zh-Hant translation was copied and modified from the zh-Hans translation, and some of them are not translated properly. This patch should fix it.

2023-10-01 16:39 UTC, pan93412 requested changes

2023-10-01 16:39 UTC, pan93412 commented on Translations-iOS/zh-Hant.xcloc/Localized Contents/zh-Hant.xliff
> +        <target>檔案</target>
```suggestion
        <target>封存檔</target>
```

```
<!-- Finder_FE.lng -->
<TextItem>
  <Description> Class = "NSTextFieldCell"; title = "Choose a password for the archive."; ObjectID = "eB2-EZ-yUs"; </Description>
  <Position>eB2-EZ-yUs.title</Position>
  <TranslationSet>
    <base loc="en">Choose a password for the archive.</base>
    <tran loc="zh-TW">選擇此封存檔的密碼。</tran>
  </TranslationSet>
</TextItem>
```

2023-10-01 16:39 UTC, pan93412 commented on Translations-iOS/zh-Hant.xcloc/Localized Contents/zh-Hant.xliff
> +        <target>新增資料夾</target>
Hmm, Apple prefers translating “Folder” to “檔案夾”. How do you think?

2023-10-01 16:39 UTC, pan93412 commented on Translations-iOS/zh-Hant.xcloc/Localized Contents/zh-Hant.xliff
> +        <target>由於記憶體限制，壓縮將限制在%lld個執行緒/s。</target>
```suggestion
        <target>由於記憶體限制，壓縮將限制在每秒%lld個執行緒。</target>
```

2023-10-01 16:39 UTC, pan93412 commented on Translations-iOS/zh-Hant.xcloc/Localized Contents/zh-Hant.xliff
> +        <target>壓縮級別越低，壓縮效果越好。「儲存」級別不壓縮，僅存檔內容。</target>
```suggestion
        <target>壓縮級別越低，壓縮效果越好。「儲存」級別不壓縮，僅封存內容。</target>
```

2023-10-01 16:43 UTC, PeterDaveHello commented on Translations-iOS/zh-Hant.xcloc/Localized Contents/zh-Hant.xliff
> +        <target>新增資料夾</target>
I believe any of the zh-Hant users will understand `資料夾` without a second thought.

2023-10-01 16:44 UTC, aonez commented
Thanks @PeterDaveHello! This translation was made using ChatGPT, so should be far from perfect. Thanks for the changes 🙌🏻

2023-10-01 16:45 UTC, PeterDaveHello commented
Oh, interesting 😆

2023-10-01 16:46 UTC, pan93412 approved these changes
LGTM

2023-10-02 08:32 UTC, aonez commented on Translations-iOS/zh-Hant.xcloc/Localized Contents/zh-Hant.xliff
> +        <target>新增資料夾</target>
Then it's better 新增資料夾 or 檔案夾? Sorry, I'm lost here.

2023-10-02 08:38 UTC, pan93412 commented on Translations-iOS/zh-Hant.xcloc/Localized Contents/zh-Hant.xliff
> +        <target>新增資料夾</target>
Both are acceptable. Why I did not resolve it is because of the missing of "Resolve" button on my side. 😢

2023-10-02 08:43 UTC, aonez commented on Translations-iOS/zh-Hant.xcloc/Localized Contents/zh-Hant.xliff
> +        <target>新增資料夾</target>
For reference this is in the Files app, "New Folder" and "untitled folder".

![image](https://github.com/aonez/Keka/assets/480163/1b32d343-f460-4884-a007-b0cbbbf94e54)

2023-10-05 07:58 UTC, merged