Electronic Book Support (FR)
aonez/Keka pull request #991
Opened 2021-12-08 17:03 UTC by Marc66

2021-12-17 22:11 UTC, Marc66 commented
Added French language for the Web site

2021-12-21 10:09 UTC, aonez requested changes

2021-12-21 10:09 UTC, aonez commented on Translations/fr.lproj/InfoPlist.strings
>  "Apple Archive" = "Apple Archive";
This one is translated in the bundled macOS extractor tool so might as well translate it 😛

2021-12-21 10:28 UTC, aonez commented
Already added the web French translation. Will fix the `l\'` string. You can't use scape inside `' '` strings but you can use scape inside `" "`.

2021-12-21 23:35 UTC, Marc66 commented
> Already added the web French translation. Will fix the `l\'` string. You can't use scape inside `' '` strings but you can use scape inside `" "`.

Thank you, looking good. Sorry for the \' string, I couldn't test while I was translating

2021-12-22 07:20 UTC, merged